server:
  port: 8080

spring:
  application:
    name: spring-boot-starter
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  profiles:
#    active: prod

springfox:
  documentation:
    swagger-ui:
      enabled: true
